apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rosebud-be.fullname" . }}
  labels:
    {{- include "rosebud-be.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "rosebud-be.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rosebud-be.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "rosebud-be.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: cert-folder
          secret:
            secretName: rosebud-certificates
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          #image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /var/data/cert/
              name: cert-folder
              readOnly: true
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
#            initialDelaySeconds: 5
#            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
#            initialDelaySeconds: 5
#            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: MYSQL_DB_NAME
              valueFrom:
                secretKeyRef:
                  key: MYSQL_DB_NAME
                  name: {{ .Values.credentialsSecretName }}
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: MYSQL_USER
                  name: {{ .Values.credentialsSecretName }}
            - name: MYSQL_PASS
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASS
                  name: {{ .Values.credentialsSecretName }}
            - name: MYSQL_SERVICE_HOST
              valueFrom:
                secretKeyRef:
                  key: MYSQL_SERVICE_HOST
                  name: {{ .Values.credentialsSecretName }}
            - name: MYSQL_SERVICE_PORT
              valueFrom:
                secretKeyRef:
                  key: MYSQL_SERVICE_PORT
                  name: {{ .Values.credentialsSecretName }}
            - name: OPENSHIFT_ALLOWED_HOST
              valueFrom:
                secretKeyRef:
                  key: OPENSHIFT_ALLOWED_HOST
                  name: {{ .Values.credentialsSecretName }}
            - name: OPENSHIFT_DUMMY_KEY
              valueFrom:
                secretKeyRef:
                  key: OPENSHIFT_DUMMY_KEY
                  name: {{ .Values.credentialsSecretName }}
            - name: COVER_API_USER
              valueFrom:
                secretKeyRef:
                  key: COVER_API_USER
                  name: {{ .Values.credentialsSecretName }}
            - name: COVER_API_PW
              valueFrom:
                secretKeyRef:
                  key: COVER_API_PW
                  name: {{ .Values.credentialsSecretName }}
            - name: SPOTIPY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: SPOTIPY_CLIENT_ID
                  name: {{ .Values.credentialsSecretName }}
            - name: SPOTIPY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: SPOTIPY_CLIENT_SECRET
                  name: {{ .Values.credentialsSecretName }}

          {{- with .Values.environment }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
