apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rosebud-be.fullname" . }}-credentials
type: Opaque
data:
  MYSQL_DB_NAME: {{ .Values.credentials.MYSQL_DB_NAME | b64enc | quote }}
  MYSQL_USER: {{ .Values.credentials.MYSQL_USER | b64enc | quote }}
  MYSQL_PASS: {{ .Values.credentials.MYSQL_PASS | b64enc | quote }}
  MYSQL_SERVICE_HOST: {{ .Values.credentials.MYSQL_SERVICE_HOST | b64enc | quote }}
  MYSQL_SERVICE_PORT: {{ .Values.credentials.MYSQL_SERVICE_PORT | b64enc | quote }}
  OPENSHIFT_ALLOWED_HOST: {{ .Values.credentials.OPENSHIFT_ALLOWED_HOST | b64enc | quote }}
  OPENSHIFT_DUMMY_KEY: {{ .Values.credentials.OPENSHIFT_DUMMY_KEY | b64enc | quote }}
  COVER_API_USER: {{ .Values.credentials.COVER_API_USER | b64enc | quote }}
  COVER_API_PW: {{ .Values.credentials.COVER_API_PW | b64enc | quote }}    
  SPOTIPY_CLIENT_ID: {{ .Values.credentials.SPOTIPY_CLIENT_ID | b64enc | quote }}    
  SPOTIPY_CLIENT_SECRET: {{ .Values.credentials.SPOTIPY_CLIENT_SECRET | b64enc | quote }}    
