{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rosebud-be.serviceAccountName" . }}
  labels:
{{ include "rosebud-be.labels" . | nindent 4 }}
{{- end -}}
