apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mongo-api.fullname" . }}
  labels:
    {{- include "mongo-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mongo-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mongo-api.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "mongo-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: properties-folder
          secret:
            secretName: mongoapi-properties
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /usr/src/app/config
              name: properties-folder
              readOnly: true
          ports:
            - name: http
              containerPort: 8339
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
              {{- with .Values.probes }}
                {{- toYaml . | nindent 14 }}
              {{- end }}
          readinessProbe:
            httpGet:
              path: /
              port: http
              {{- with .Values.probes }}
                {{- toYaml . | nindent 14 }}
              {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
